# From https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

name: Test with pytest

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python_version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi pytest 'typing;python_version<"3.5"'
    - name: Run pytest
      run: pytest
