# From https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

name: Test with pytest

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - python:3.4-slim
          - python:3.5-slim
          - python:3.6-slim
          - python:3.7-slim
          - python:3.8-slim
          - python:3.9-slim
          - python:3-slim
          - pypy:3-slim

    container:
        image: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi pytest 'typing;python_version<"3.5"'
    - name: Run pytest
      run: pytest
